version: "3"

services:
    web:
        image: tuxgasy/dolibarr
        depends_on:
            - pgdb
        environment:
            DOLI_DB_HOST: pgdb
            DOLI_DB_USER: db_user
            DOLI_DB_PASSWORD: dbpass
            DOLI_DB_NAME: crm_db
            DOLI_URL_ROOT: 'http://0.0.0.0'
            PHP_INI_DATE_TIMEZONE: 'Europe/AT'
            DOLI_DB_TYPE: pgsql
            DOLI_DB_HOST_PORT: 5432
        ports:
            - "8080:80"

    pgdb:
        image: postgres:latest
        environment:
            - POSTGRES_DB=crm_db
            - POSTGRES_PASSWORD=dbpass
            - POSTGRES_USER=db_user
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"