# This docker-compose.yml file is used to build and test quickly
# a specific version of Dolibarr
#
# Before build, define the variable DOLI_VERSION as following:
# $ export DOLI_VERSION=4.0.4
# And then, you can run :
# $ docker-compose up
#
# More information about Docker-compose : https://docs.docker.com/compose/

version: "3.8"

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

secrets:
    pg-user:
        file: ./secrets/pg_user.secret
    pg-password:
        file: ./secrets/pg_password.secret

services:
    pgdb:
        image: pgdb:latest
        secrets:
            - pg_user
            - pg-password
        environment:
            POSTGRES_DB: dolibarr_db
            POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
            POSTGRES_USER: dolibarr
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - internal-pod

    cron:
        build:
            context: ./docker-compose-links/${DOLI_VERSION}${PHP_VERSION}
        image: tuxgasy/dolibarr:${DOLI_VERSION}${PHP_VERSION}
        secrets:
            - pg-user
            - pg-password
        environment:
            DOLI_CRON: 1
            DOLI_CRON_KEY: xxxx
            DOLI_CRON_USER: administrator
            DOLI_DB_USER_FILE: /run/secrets/pg-user
            DOLI_DB_PASSWORD_FILE: /run/secrets/pg-password
            DOLI_ADMIN_LOGIN: admin
            DOLI_ADMIN_PASSWORD: admin
            DOLI_DB_HOST: pgdb
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: http://0.0.0.0
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        networks:
            - internal-pod

    web:
        build:
            context: ./docker-compose-links/${DOLI_VERSION}${PHP_VERSION}
        image: tuxgasy/dolibarr:${DOLI_VERSION}${PHP_VERSION}
        secrets:
            - mysql-user
            - mysql-password
        volumes:
            - ./.volumes/dolibarr/custom:/var/www/html/custom
        depends_on:
            - pgdb
        environment:
            DOLI_DB_USER_FILE: "/run/secrets/pg-user"
            DOLI_DB_PASSWORD_FILE: "/run/secrets/pg-password"
            DOLI_ADMIN_LOGIN: "admin"
            DOLI_ADMIN_PASSWORD: "admin"
            DOLI_DB_HOST: pgdb
            DOLI_DB_NAME: dolibarr_db
            DOLI_URL_ROOT: 'http://0.0.0.0'
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "80:80"
        networks:
            - internal-pod
            - external-pod